baseURL = 'https://adrianlaynez.dev/'
languageCode = 'es'
title = 'Hello Attention'
theme = 'PaperMod'
publishDir = "docs"

[params]
  defaultTheme = "auto"
  # Tu nombre en la home
  author = "Adri치n Laynez Ortiz"
  # Descripci칩n corta debajo de tu nombre
  homeInfoParams.Title = "Hello Attention 游녦"
  homeInfoParams.Content = "Estudiante de Mates e Inform치tica. Construyendo un GPT desde cero en C++."

  # Enlaces a tus redes (GitHub, etc)
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/adrilaynez"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/tu-usuario"  # C치mbialo cuando tengas
    [params.assets]
  disableFingerprinting = true
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Proyectos"
    url = "/projects/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Etiquetas"
    url = "/tags/"
    weight = 30